matrix:
  include:
    - language: generic
      notifications:
        email: false
      addons:
        apt:
          packages:
            - aspell
            - aspell-en
            - dictionaries-common
      script:
        - ./check-spelling.sh
    
    - language: generic
      notifications:
        email: false
      services:
        - docker
      before_install:
        - docker pull antidotelabs/syringe:latest
        - docker run -v $(pwd):/antidote antidotelabs/syringe syrctl validate /antidote
      install:
        - ./check-changelog.sh
      sudo: false