language: generic
notifications:
  email: false
services:
  - docker
before_install:
  - docker pull antidotelabs/antidote-core:latest
  - docker run -v $(pwd):/antidote antidotelabs/antidote-core antidote validate /antidote
install:
  - ./check-changelog.sh
sudo: false
