---
lessonName: Automating the Troubleshooting Chain
lessonId: 21
category: workflows
tier: prod

# TODO(mierdin): add Python when there is a lesson for it
prereqs:
  - 23  # Linux
description: In this lesson, we'll explore the use of some custom Python scripts for doing some automated troubleshooting.
slug: Automated Troubleshooting
tags:
- troubleshooting
- tshoot

endpoints:
- name: linux1
  image: antidotelabs/utility
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: sipphone
  image: antidotelabs/pjsua-lindsey
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: vqfx1
  image: antidotelabs/vqfx-snap1
  configurationType: napalm-junos
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: vqfx2
  image: antidotelabs/vqfx-snap2
  configurationType: napalm-junos
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: asterisk
  image: antidotelabs/asterisk
  additionalPorts: [8088]

# For future version of lesson
#
# - name: netbox
#   image: antidotelabs/netbox
#   additionalPorts: [8000]


connections:
- a: vqfx1
  b: vqfx2
- a: vqfx2
  b: sipphone
- a: vqfx1
  b: asterisk


stages:
  - id: 1
    description: Get the IP Address for a Phone Extension
