---
- name: Ansible test within NRE Labs lesson
  hosts: vqfx1
  gather_facts: no

  tasks:

  # https://docs.ansible.com/ansible/latest/modules/junos_banner_module.html
  - name: configure the login banner
    junos_banner:
      banner: login
      port: 22  # Getting a deprecation warning for this but the docs don't say anything about it
      text: |
        this is my login banner
        that contains a multiline
        string
      state: present
