---
lessonName: Working with REST APIs
lessonId: 19
category: fundamentals
lessondiagram: https://raw.githubusercontent.com/nre-learning/nrelabs-curriculum/v0.3.2/lessons/lesson-19/lessondiagram.png
tier: prod
prereqs:
  - 22  # Python
  - 23  # Linux
description: REST APIs are an extremely popular, flexible option for remote programmability of a network device. In this lesson, we'll cover the basics of REST APIs, interact with one in the bash shell as well as Python, and prepare for using them for higher-order workflows in later lessons.
slug: REST APIs
tags:
- rest
- api
- rest api
- programmability


endpoints:

- name: linux1
  image: antidotelabs/utility
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: vqfx1
  image: antidotelabs/vqfx-snap1
  configurationType: napalm-junos
  presentations:
  - name: cli
    port: 22
    type: ssh

  # This may not work
  - name: explorer
    port: 8080
    type: http

# Tbh this should probably be something that starts off much simpler and builds.
# This was built as a very early PoC (one of the very first lesson) and it really
# seems to sprint towards the point of just calling a full blown network device API.
# Maybe a mixture of APIs, both for networking and not, taking a lot longer along the
# way to cover a breadth of subtopics.

# TODO(mierdin): Insert generic REST server with tracing enabled

stages:
  - id: 1
    description: Your First API Call

  - id: 2
    description: Let's do it with Python!
  # 3:
  #   description: Diving Deep into an API
