---
name: Terraform & Junos
slug: terraform-junos
category: tools
diagram: https://raw.githubusercontent.com/nre-learning/nrelabs-curriculum/v0.3.2/lessons/lesson-31/lessondiagram.png
description: Terraform provides a declarative way of managing resources and now you can experiment with controlling Junos resources through this exciting lesson! 
tier: prod
shortDescription: Terraform
tags:
  - terraform
  - declarative
  - junos

endpoints:
- name: terraform1
  image: terraform
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: vqfx1
  image: vqfx-snap1
  configurationType: napalm
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: vqfx2
  image: vqfx-snap2
  configurationType: napalm
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: vqfx3
  image: vqfx-snap3
  configurationType: napalm
  presentations:
  - name: cli
    port: 22
    type: ssh

connections:
- a: vqfx1
  b: vqfx2
- a: vqfx2
  b: vqfx3
- a: vqfx3
  b: vqfx1

stages:
  - description: Terraform Init
    guideType: markdown

  - description: Terraform Plan
    guideType: markdown

  - description: Terraform Apply
    guideType: markdown

  - description: Terraform Destroy
    guideType: markdown

  - description: Terraform Bonus
    guideType: markdown
