---
- name: gather information from routers
  hosts: juniper
  gather_facts: True

  tasks:
    - name: display version
      debug:
        msg: "The Junos version is: {{ ansible_net_version }}"

    - name: display serial number
      debug:
        msg: "The serial number is:{{ ansible_net_serialnum }}"
