---
hosts:
  - device: junos1
    username : antidote
    passwd: antidotepassword
    port: 22
  - device: junos2
    username : antidote
    passwd: antidotepassword
    port: 22
  - device: junos3
    username : antidote
    passwd: antidotepassword
    port: 22
tests:
    - jsnapy_tests.yaml
