---
name: Network Unit Testing with JSNAPY
slug: jsnapy-network-testing
category: tools
diagram: https://raw.githubusercontent.com/nre-learning/nrelabs-curriculum/v0.3.2/lessons/lesson-12/lessondiagram.png
tier: prod
prereqs:
  - yaml-introduction
  - linux-basics
description: Unit testing your network devices is one of the fundamental building blocks to CI/CD for networking. In this lesson, we'll explore the use of an open source tool - JSNAPy - for doing just this with Junos devices.
shortDescription: JSNAPy
tags:
- jsnapy
- test
- unit test
- testing
collection: juniper-networks

authors:
- name: Matt Oswalt
  link: https://oswalt.dev

endpoints:
- name: linux1
  image: utility
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: junos1
  image: crpd
  # configurationType: napalm
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: junos2
  image: crpd
  # configurationType: napalm
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: junos3
  image: crpd
  # configurationType: napalm
  presentations:
  - name: cli
    port: 22
    type: ssh

connections:
- a: junos1
  b: junos2
  subnet: 10.12.0.0/24
- a: junos2
  b: junos3
  subnet: 10.23.0.0/24
- a: junos3
  b: junos1
  subnet: 10.31.0.0/24

stages:
  - description: No BGP config - Tests Fail
    guideType: markdown

  - description: Correct BGP config - Tests Pass
    guideType: markdown

